id = "angular-snippets"
name = "Angular TypeScript Snippets"
version = "21.0.0"
schema_version = 1
authors = ["hudson-newey", "johnpapa"]
description = "Angular 20 TypeScript snippets for the Zed IDE"
repository = "https://github.com/hudson-newey/angular-snippets-for-zed"
# snippets = ["./snippets/angular.json", "./snippets/typescript.json"] # this doesn't work, although I'd like it to...
snippets = "./snippets/typescript.json"
