id = "zed-angular-snippets"
name = "Zed Angular Snippets"
version = "21.0.0"
schema_version = 1
authors = ["hudson-newey", "johnpapa"]
description = "Angular snippets for Zed (fork of johnpapa/vscode-angular-snippets)"
repository = "https://github.com/hudson-newey/zed-angular-snippets"
# snippets = ["./snippets/angular.json", "./snippets/typescript.json"] # this doesn't work, although I'd like it to...
snippets = "./snippets/typescript.json"
