id = "zed-angular-snippets"
name = "Zed Angular Snippets"
version = "0.1.0"
schema_version = 1
authors = ["hudson-newey", "johnpapa"]
description = "Angular snippets for Zed (fork of johnpapa/vscode-angular-snippets)"
repository = "https://github.com/hudson-newey/zed-angular-snippets"
snippets = ["./snippets/angular.json", "./snippets/typescript.json"]
